node {
    checkout scm
  
        stage('Build')
        {   
            withDockerContainer(image:'python:2-alpine')
            {
                 sh 'python -m py_compile sources/add2vals.py sources/calc.py'
                 stash(name: 'compiled-results', includes: 'sources/*.py*')
            }
        }

        stage('Test')
        { 
            withDockerContainer(args:'-p 3000:3000', image:'qnib/pytest')
            {
                sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            }
        }
}
